#!/bin/bash
a="Apple"
al="ArchLinux"
c="Chrome"
d="Debain"
k="KaliLinux"
f="fendora"
u="Ubantu"
w="Window"
clear
echo " "
echo " Choosing An                 by Stephan"
figlet -f Univers "    OS"
#echo "                 Choosing An OS"
echo "                         |"
echo "                         |"
echo "            Do You Enjoy Learning Teachnology ?"
echo "                         |"
echo "                         |"
echo "                 ________|_________" 
echo "                |                  |"
echo "               No                 Yes"
echo "                |                  |___________________ " 
echo "        Is Your daddy rich?                           | "
echo "                |                          Do You care about Freedom/Privacy" 
echo "      __________|___________                          |"
echo "     |                      |                 ________|_________ "
echo "    Yes                     No               |                  | "            
echo "     |                      |               Yes                 No "  
echo "(Apple iMac)          (Google Chromebook)    |               (Window) "
echo "                                             |"
echo "                                     Do You have Life ?"
echo "                                             | "
echo "                                   __________|___________"
echo "                                  |                      |"
echo "                                  Yes                    No"
echo "                                  |                      |_____(Kali Linux) "
echo "                       ___________|_________             | "
echo "                      |           |        |             |"
echo "                   Ubantu      Debian     Fendora        |_____(Arch Linux) "
echo " "
